WineViewWeb2/Areas/Admin/Controllers/BodyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WineView2.DataAccess.Repository.IRepository;
using WineView2.Models.ViewModels;
using WineView2.Models;
using WineView2.Utility;

namespace BodyView2Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Producer)]
    public class BodyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public BodyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Body body = new Body();
            if (id != null && id != 0)
            {
                //update
                body = _unitOfWork.Body.Get(u => u.Id == id);
            }
            return View(body);
        }

        [HttpPost]
        public IActionResult Upsert(Body body)
        {
            if (ModelState.IsValid)
            {

                if (body.Id == 0)
                {
                    _unitOfWork.Body.Add(body);
                }
                else
                {
                    _unitOfWork.Body.Update(body);
                }
                _unitOfWork.Save();
                TempData["success"] = "Body created successfully";
                return RedirectToAction("Index");
            }
            return View(body);
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Body> objBodyList = _unitOfWork.Body.GetAll().ToList();
            return Json(new { data = objBodyList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var bodyToBeDeleted = _unitOfWork.Body.Get(u => u.Id == id);
            if (bodyToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.Body.Remove(bodyToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion
    }
}

WineViewWeb2/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WineView2.DataAccess.Data;
using WineView2.DataAccess.Repository.IRepository;
using WineView2.Models;
using WineView2.Models.ViewModels;
using WineView2.Utility;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace WineView2Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IUnitOfWork _unitOfWork;
        public UserController(UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork, RoleManager<IdentityRole> roleManager)
        {
            _unitOfWork = unitOfWork;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RoleManagment(string userId)
        {

            RoleManagmentVM RoleVM = new RoleManagmentVM()
            {
                ApplicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == userId),
                RoleList = _roleManager.Roles.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Name
                })
            };

            RoleVM.ApplicationUser.Role = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == userId))
                    .GetAwaiter().GetResult().FirstOrDefault();
            return View(RoleVM);
        }

        [HttpPost]
        public IActionResult RoleManagment(RoleManagmentVM roleManagmentVM)
        {

            string oldRole = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == roleManagmentVM.ApplicationUser.Id))
                    .GetAwaiter().GetResult().FirstOrDefault();

            ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == roleManagmentVM.ApplicationUser.Id, tracked:true);

            if (!(roleManagmentVM.ApplicationUser.Role == oldRole))
            {
                //a role was updated

                _userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
                _userManager.AddToRoleAsync(applicationUser, roleManagmentVM.ApplicationUser.Role).GetAwaiter().GetResult();
            }

            return RedirectToAction("Index");
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<ApplicationUser> objUserList = _unitOfWork.ApplicationUser.GetAll().ToList();

            foreach (var user in objUserList)
            {
                user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();
            }
            return Json(new { data = objUserList });
        }

        #endregion
    }
}

WineViewWeb2/Areas/Admin/Controllers/WineController.cs
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using System.Security.Claims;
using System.Text;
using WineView2.DataAccess.Repository.IRepository;
using WineView2.Models;
using WineView2.Models.ViewModels;
using WineView2.Utility;

namespace WineView2Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Producer)]
    public class WineController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly string _storageConnectionString;

        public WineController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment, IConfiguration configuration)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
            _storageConnectionString = configuration.GetConnectionString("AzureStorage");
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            WineVM wineVM = new()
            {
                Wine = new(),
                ColorList = _unitOfWork.Color.GetAll().Select(
                u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }
                ),
                WineryList = _unitOfWork.Winery.GetAll().Select(
                u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }
                ),
                StyleList = _unitOfWork.Style.GetAll().Select(
                u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }
                ),
                GrapeList = _unitOfWork.Grape.GetAll().Select(
                u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }
                )
            };

            if (id == null || id == 0)
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                wineVM.Wine.Creator = _unitOfWork.ApplicationUser.Get(u => u.Id == userId);
                //create
                return View(wineVM);
            }
            else
            {
                //update
                wineVM.Wine = _unitOfWork.Wine.Get(u => u.Id == id, includeProperties: "Grapes");
                wineVM.GrapeList = _unitOfWork.Grape.GetAll().Select(
                                        u => new SelectListItem
                                        {
                                            Text = u.Name,
                                            Value = u.Id.ToString(),
                                            Selected = wineVM.Wine.Grapes.Select(g => g.Id).Contains(u.Id)
                                        });
                return View(wineVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(WineVM wineVM, IFormFile? file, string[]? grapes)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string winePath = Path.Combine(wwwRootPath, @"images\wine");

                    if (!string.IsNullOrEmpty(wineVM.Wine.ImageUrl))
                    {
                        //delete the old image
                        var oldImagePath =
                            Path.Combine(wwwRootPath, wineVM.Wine.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(winePath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    wineVM.Wine.ImageUrl = @"\images\wine\" + fileName;
                }

                if (grapes != null)
                {
                    var items = _unitOfWork.Grape.GetAll().Select(
                                u => new SelectListItem
                                {
                                    Text = u.Name,
                                    Value = u.Id.ToString()
                                }
                                );
                    wineVM.Wine.Grapes = new();
                    foreach (SelectListItem item in items)
                    {
                        if (grapes.Contains(item.Value))
                        {
                            Grape grapeFromDb = _unitOfWork.Grape.Get(u => u.Id.ToString() == item.Value, tracked:true);
                            wineVM.Wine.Grapes.Add(grapeFromDb);
                        }
                    }
                }

                StringBuilder grapeNames = new StringBuilder();
                for (int i = 0; i < wineVM.Wine.Grapes.Count; i++)
                {
                    grapeNames.Append(wineVM.Wine.Grapes[i].Name);
                    if (i < wineVM.Wine.Grapes.Count - 1)
                    {
                        grapeNames.Append(", ");
                    }
                }
                var colorName = _unitOfWork.Color.Get(u => u.Id == wineVM.Wine.ColorId).Name;
                var styleName = _unitOfWork.Style.Get(u => u.Id == wineVM.Wine.StyleId).Name;

                wineVM.Wine.FullName = wineVM.Wine.Name + " " + grapeNames.ToString() + ", " + colorName + ", " + styleName;

                if (wineVM.Wine.Id == 0)
                {
                    var claimsIdentity = (ClaimsIdentity)User.Identity;
                    var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                    wineVM.Wine.ApplicationUserId = userId;

                    if (wineVM.Wine.ImageUrl == null)
                    {
                        wineVM.Wine.ImageUrl = "";
                    }

                    _unitOfWork.Wine.Add(wineVM.Wine);
                    TempData["success"] = "Wine created successfully";
                }
                else
                {
                    Wine wineFromDb = _unitOfWork.Wine.Get(u => u.Id == wineVM.Wine.Id, includeProperties: "Grapes", tracked:true);

                    var claimsIdentity = (ClaimsIdentity)User.Identity;
                    var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                    if (wineFromDb.ApplicationUserId != userId && !(User.IsInRole(SD.Role_Admin)))
                    {
                        return Json(new { success = false, message = "No access" });
                    }

                    wineFromDb.Grapes.RemoveAll(u => true);

                    _unitOfWork.Wine.Update(wineVM.Wine);
                    TempData["success"] = "Wine updated successfully";
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            wineVM.ColorList = _unitOfWork.Color.GetAll().Select(
            u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }
            );
            wineVM.WineryList = _unitOfWork.Winery.GetAll().Select(
            u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }
            );
            wineVM.StyleList = _unitOfWork.Style.GetAll().Select(
            u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }
            );
            wineVM.GrapeList = _unitOfWork.Grape.GetAll().Select(
            u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
                Selected = grapes.Contains(u.Id.ToString())
            });
            return View(wineVM);
        }

/*        [HttpGet]
        public async Task<IActionResult> Forecast(int? id)
        {
            string url = $"http://localhost:5002/wine_data?wineId={id}";

            using HttpClient client = new HttpClient();
            HttpResponseMessage response = await client.GetAsync(url);

            if (response.IsSuccessStatusCode)
            {
                string zipFileName = await response.Content.ReadAsStringAsync();
                // Azure Blob Storage connection details
                string connectionString = "Your_Azure_Storage_Connection_String";
                string containerName = "forecast";

                // Create a BlobServiceClient
                BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);

                // Get a reference to the container
                BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);

                // Get a reference to the blob (file)
                BlobClient blobClient = containerClient.GetBlobClient(zipFileName);

                // Download the blob to a MemoryStream
                MemoryStream memoryStream = new MemoryStream();
                await blobClient.DownloadToAsync(memoryStream);

                // Reset the stream position to the beginning
                memoryStream.Position = 0;

                // Return the file as a download
                return File(memoryStream, "application/zip", zipFileName);
            }
            else

WineViewWeb2/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WineView2.DataAccess.Repository.IRepository;
using WineView2.Utility;

namespace WineView2Web.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {

        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                    _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).Count());
                }

                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }

    }
}

WineViewWeb2/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WineView2Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/WineView2Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.7/css/dataTables.dataTables.min.css" />
    <link rel="icon" type="image/x-icon" href="~/images/favicon.ico">  
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WineView</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Producer) || User.IsInRole(SD.Role_User))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Review" asp-action="Index">Reviews</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Classify">Detect Wines</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Producer))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Review" asp-action="CreatorReviews">Wine Reviews</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Wine" asp-action="Index">Wine</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Winery" asp-action="Index">Winery</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Grape" asp-action="Index">Grape</a>
                                    </li>
                                    @if (User.IsInRole(SD.Role_Admin))
                                    {
                                        <li class="nav-item">
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="Color" asp-action="Index">Color</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="Style" asp-action="Index">Style</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="Body" asp-action="Index">Body</a>
                                        </li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li class="nav-item">
                                            <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                        </li>
                                    }
                                </ul>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

@*     <footer class="border-top footer bg-primary">
        <div class="text-center">
            Made with <i class="bi bi-heart-fill"></i> by Radu
        </div>
    </footer> *@
    <footer class="border-top footer text-muted fixed-bottom" style="background-color:lightblue;">
        <div class="container" style="color: black">
            &copy; 2024 - WineViewWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/2.0.7/js/dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WineViewWeb2/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}