WineViewWeb2/Areas/Admin/Controllers/WineryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WineView2.DataAccess.Repository.IRepository;
using WineView2.Models.ViewModels;
using WineView2.Models;
using WineView2.Utility;

namespace WineryView2Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Producer)]
    public class WineryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public WineryController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Winery winery = new Winery();
            if (id != null && id != 0)
            {
                //update
                winery = _unitOfWork.Winery.Get(u => u.Id == id);
            }
            return View(winery);
        }

        [HttpPost]
        public IActionResult Upsert(Winery winery)
        {
            if (ModelState.IsValid)
            {

                if (winery.Id == 0)
                {
                    _unitOfWork.Winery.Add(winery);
                }
                else
                {
                    _unitOfWork.Winery.Update(winery);
                }
                _unitOfWork.Save();
                TempData["success"] = "Winery created successfully";
                return RedirectToAction("Index");
            }
            return View(winery);
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Winery> objWineryList = _unitOfWork.Winery.GetAll().ToList();
            return Json(new { data = objWineryList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var wineryToBeDeleted = _unitOfWork.Winery.Get(u => u.Id == id);
            if (wineryToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.Winery.Remove(wineryToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion
    }
}

WineViewWeb2/Areas/Admin/Views/Winery/Index.cshtml
<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Winery List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Winery" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i>  Create New Winery
                </a>
            </div>
        </div>

        <table id="tblData" class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Region</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts {
    <script src="~/js/winery.js"></script>
}

WineViewWeb2/Areas/Admin/Views/Winery/Upsert.cshtml
@model Winery

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">@(Model.Id != 0 ? "Update" : "Create") Winery</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="row">
                <div class="col-10">
                    <div class="border p-3">
                        <div asp-validation-summary="ModelOnly"></div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Name" class="form-control border-0 shadow" />
                            <label asp-for="Name" class="ms-2"></label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Region" class="form-control border-0 shadow" />
                            <label asp-for="Region" class="ms-2"></label>
                            <span asp-validation-for="Region" class="text-danger"></span>
                        </div>

                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Winery" asp-action="Index" class="btn btn-outline-primary border  form-control">
                                    Back to List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}